planner/recipes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class RecipeForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    time = StringField("Time", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    ingredient_name = StringField("Ingredient[]")
    ingredient_amount = StringField("Amount[]")
    submit = SubmitField("Post")

planner/scraper/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, URL


class ScraperForm(FlaskForm):
    recipe_url = StringField("Recipe url", validators=[DataRequired(), URL()])
    submit = SubmitField("Scrape")

planner/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from planner.models import User


class RegistrationForm(FlaskForm):
    username = StringField(
        "Username", validators=[DataRequired(), Length(min=2, max=20)]
    )
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField(
        "Confirm Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("Username taken. Choose a different username")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("Email taken. Choose a different username")


class RequestResetForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Request Password Reset")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError(
                "No account with that email exists. Are you sure you used that email to create your user?"
            )


class ResetPasswordForm(FlaskForm):
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField(
        "Confirm Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Reset Password")


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember = BooleanField("Remember me")
    submit = SubmitField("Log in")


class UpdateAccountForm(FlaskForm):
    username = StringField(
        "Username", validators=[DataRequired(), Length(min=2, max=20)]
    )
    email = StringField("Email", validators=[DataRequired(), Email()])
    picture = FileField(
        "Update profile picture", validators=[FileAllowed(["jpg", "png"])]
    )
    submit = SubmitField("Update")

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError("Username taken. Choose a different username")

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError("Email taken. Choose a different username")

planner/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy

from planner.config import Config


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message_category = "info"
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from planner.users.routes import users
    from planner.recipes.routes import recipes
    from planner.main.routes import main
    from planner.scraper.routes import scrap
    from planner.shopping_list.routes import shopping

    app.register_blueprint(users)
    app.register_blueprint(recipes)
    app.register_blueprint(main)
    app.register_blueprint(scrap)
    app.register_blueprint(shopping)

    return app

planner/main/routes.py
from flask import Blueprint, render_template, request

from planner.models import Recipe

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get("page", 1, type=int)
    recipe_list = Recipe.query.order_by(Recipe.date_posted.desc()).paginate(
        page=page, per_page=5
    )
    return render_template("home.html", recipe_list=recipe_list, title="Home")


@main.route("/about")
def about():
    return render_template("about.html", title="About")

planner/recipes/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from planner import db
from planner.models import Recipe, Ingredient
from planner.recipes.forms import RecipeForm


recipes = Blueprint("recipes", __name__)


@recipes.route("/recipe/new", methods=["GET", "POST"])
@login_required
def new_recipe():
    form = RecipeForm()
    if form.validate_on_submit():
        ingredients = [
            Ingredient(name=x, amount=y)
            for x, y in (
                zip(
                    request.form.getlist("ingredient_name"),
                    request.form.getlist("ingredient_amount"),
                )
            )
        ]
        recipe = Recipe(
            title=form.title.data,
            time=form.time.data,
            text=form.text.data,
            author=current_user,
            ingredients=ingredients,
        )
        db.session.add(recipe)
        db.session.commit()
        flash("Your recipe has been created", "success")
        return redirect(url_for("main.home"))
    return render_template(
        "create_recipe.html",
        title="New Recipe",
        form=form,
        ingredients=[Ingredient(name="", amount="")],
    )


@recipes.route("/recipe/<recipe_id>")
@login_required
def recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    return render_template("recipe.html", title=recipe.title, recipe=recipe)


@recipes.route("/recipe/<recipe_id>/update", methods=["GET", "POST"])
@login_required
def update_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if current_user != recipe.author:
        abort(403)
    form = RecipeForm()
    if form.validate_on_submit():
        ingredients = [
            Ingredient(name=x, amount=y)
            for x, y in (
                zip(
                    request.form.getlist("ingredient_name"),
                    request.form.getlist("ingredient_amount"),
                )
            )
        ]
        recipe.title = form.title.data
        recipe.time = form.time.data
        recipe.text = form.text.data
        for ingredient in recipe.ingredients:
            db.session.delete(ingredient)
        recipe.ingredients = ingredients
        db.session.commit()
        flash("Your recipe has been updated", "success")
        return redirect(url_for("recipes.recipe", recipe_id=recipe.id))
    elif request.method == "GET":
        form.title.data = recipe.title
        form.time.data = recipe.time
        form.text.data = recipe.text
    return render_template(
        "create_recipe.html",
        title="Update Recipe",
        form=form,
        ingredients=recipe.ingredients,
    )


@recipes.route("/recipe/<recipe_id>/delete", methods=["POST"])
@login_required
def delete_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if current_user != recipe.author:
        abort(403)
    for ingredient in recipe.ingredients:
        db.session.delete(ingredient)
    db.session.delete(recipe)
    db.session.commit()
    flash("Your recipe has been deleted", "success")
    return redirect(url_for("main.home"))


@recipes.route("/recipe/<recipe_id>/shoplist")
@login_required
def shop_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if current_user in recipe.fans:
        recipe.fans.remove(current_user)
    else:
        recipe.fans.append(current_user)
    db.session.commit()
    return redirect(url_for("main.home"))

planner/scraper/__init__.py
from requests_html import HTMLSession


def scrape(url):
    if "lidl" in url:
        return lidl(url)
    return None


def lidl(url):
    try:
        session = HTMLSession()
        r = session.get(url)
        ingredients_html = r.html.find("div.skladniki", first=True).find("li")
        name = r.html.find("div.lead", first=True).find("h1", first=True)
        time = r.html.find("li.meta_time", first=True).find("strong", first=True)
        recipe_text = r.html.find("div.article#opis", first=True)
        return {
            "name": name.text,
            "time": time.text,
            "text": recipe_text.text,
            "ingredients": lidl_ingredients(ingredients_html),
        }
    except Exception as ex:
        return None


def lidl_ingredients(ingredients):
    for ingredient in ingredients:
        yield tuple(ingredient.text.split(" – "))

planner/scraper/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_login import current_user, login_required

from planner import db
from planner.models import Ingredient, Recipe
from . import scrape
from .forms import ScraperForm

scrap = Blueprint("scrap", __name__)


@scrap.route("/scraper", methods=["POST"])
@login_required
def scraper():
    form = ScraperForm()
    form.recipe_url.data = request.form.get("recipe_url")
    recipe_scr = scrape(form.recipe_url.data)
    if recipe_scr:
        recipe = Recipe(
            title=recipe_scr["name"],
            time=recipe_scr["time"],
            text=recipe_scr["text"],
            author=current_user,
        )
        recipe.ingredients = [
            Ingredient(name=x, amount=y[0] if y else "")
            for x, *y in recipe_scr["ingredients"]
        ]
        db.session.add(recipe)
        db.session.commit()
        flash(f"The recipe has been imported!", "success")
        return redirect(url_for("recipes.recipe", recipe_id=recipe.id))
    flash(f"Something went wrong - please try again", "danger")
    return render_template("scraper.html", title="Scraper", form=form)

planner/shopping_list/routes.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    flash,
    redirect,
    request,
    current_app,
)
from flask_login import current_user, login_required
from planner import db
from planner.models import Recipe
from keep import export_to_keep

shopping = Blueprint("shopping", __name__)


@shopping.route("/shopping_list")
@login_required
def shopping_list():
    page = request.args.get("page", 1, type=int)
    recipe_list = (
        Recipe.query.join(Recipe.fans)
        .filter_by(email=current_user.email)
        .paginate(page=page, per_page=5)
    )
    return render_template(
        "shopping_list.html", recipe_list=recipe_list, title="Shopping list"
    )


@shopping.route("/shopping_list/export")
@login_required
def export():
    recipes = current_user.favorite_recipes
    flash_msg = export_to_keep(
        recipes,
        current_app.config["MAIL_USERNAME"],
        current_app.config["MAIL_PASSWORD"],
        current_user.email,
    )
    flash(flash_msg, "success")
    return redirect(url_for("shopping.shopping_list"))


@shopping.route("/shopping_list/<recipe_id>/remove")
@login_required
def shopping_list_remove_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if current_user in recipe.fans:
        recipe.fans.remove(current_user)
        db.session.commit()
    return redirect(url_for("shopping.shopping_list"))

planner/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required, login_user, logout_user
from planner import db, bcrypt
from planner.models import User, Recipe
from planner.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from planner.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_pw
        )
        db.session.add(user)
        db.session.commit()
        flash(f"Your account has been created!", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login unsuccessful. Please check email and password", "danger")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout", methods=["GET"])
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename=f"profile_pics/{current_user.image_file}")
    return render_template(
        "account.html", title="Account", image_file=image_file, form=form
    )


@users.route("/user/<string:username>")
def user_recipes(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    recipe_list = (
        Recipe.query.filter_by(author=user)
        .order_by(Recipe.date_posted.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("user_recipes.html", recipe_list=recipe_list, user=user)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Reset password email has been sent", "info")
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<string:token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid/expired token", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user.password = hashed_pw
        db.session.commit()
        flash(f"Your password has been updated!", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)

planner/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page!</h1>
{% endblock content %}

planner/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <a class="btn btn-primary btn-lg mt-1 mb-1" href="#scraperModal" data-toggle="modal" data-target="#scraperModal">Import recipe</a>
    <a class="btn btn-primary btn-lg mt-1 mb-1" href="{{ url_for('recipes.new_recipe') }}">New Recipe</a>
    {% for recipe in recipe_list.items %}
        <article class="content-section">
            <div class="article-metadata">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+ recipe.author.image_file) }}">
                <a class="mr-2" href="{{ url_for('users.user_recipes', username=recipe.author.username) }}">{{ recipe.author.username }}</a>
                <small class="text-muted">{{ recipe.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
            </div>
            <p class="lead">
                {% if current_user in recipe.fans %}
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('recipes.shop_recipe', recipe_id=recipe.id) }}">Remove from shopping list</a>
                {% else %}
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('recipes.shop_recipe', recipe_id=recipe.id) }}">Add to shopping list</a>
                {% endif %} 
                <br><a class="article-title" href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}"">{{ recipe.title }}</a>      
            </p>
            <small class="text-muted">Składniki: {{recipe.ingredients|length}} | Czas: {{ recipe.time }}</small>
        </article>
    {% endfor %}
    {% for page_num in recipe_list.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if recipe_list.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

{% endblock content %}

planner/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        <title>Planer diety i zakupów{% if title %} - {{ title }}{% endif %}</title>
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Planner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Recipes</a>
                        <a class="nav-item nav-link" href="{{ url_for('shopping.shopping_list') }}">Shopping list</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log out</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Log in</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>
                </div>
            </div>
            </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                    <div class="col"></div>
                <div class="col-md-10">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor%}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                <div class="col"></div>
            </div>
        </main>


        <!-- Modal -->
        <div class="modal fade" id="scraperModal" tabindex="-1" role="dialog" aria-labelledby="scraperModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="scraperModalLabel">Import recipe from a different page</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{{ url_for('scrap.scraper') }}" method="POST">
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="form-control-label" for="recipe_url">Recipe url</label>
                            <input class="form-control mr-1 ml-1" id="recipe_url" name="recipe_url" required="" type="text" value="">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input class="btn btn-outline-info" id="submit" name="submit" type="submit" value="Start importing">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

planner/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input")}}
                    {{ form.remember.label(class="form-check-label")}}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register Now</a>
        </small>
    </div>
{% endblock content %}

planner/templates/recipe.html
{% extends "layout.html" %}
{% block content %}
    <article class="content-section">
        <div class="article-metadata">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+ recipe.author.image_file) }}">
            <a class="mr-2" href="{{ url_for('users.user_recipes', username=recipe.author.username) }}">{{ recipe.author.username }}</a>
            <small class="text-muted">{{ recipe.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
            {% if recipe.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('recipes.update_recipe', recipe_id=recipe.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
        </div>
        <p class="lead">{{ recipe.title }}</p>
        <p>Składniki:
            <ul class="list">
                {% for ingr in recipe.ingredients %}
                    <li>{{ ingr.name }}{% if ingr.amount %}: {{ ingr.amount }} {{ ingr.unit }}{% endif %}</li>
                {% endfor %}
            </ul>
        </p>
        <p>Czas: {{ recipe.time }}</p>
        <p>Przepis:
            {{ recipe.text }}
        </p>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete recipe?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

planner/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

planner/templates/shopping_list.html
{% extends "layout.html" %}
{% block content %}
    {% if recipe_list.items %}
        <a class="btn btn-primary btn-lg mt-1 mb-1" href="{{ url_for('shopping.export') }}">Send to Google Keep</a><br>
    {% else %}
        <h1>Your shopping list is empty :(</h1>
        <h3><a class="btn btn-primary btn-lg mt-1 mb-1" href="{{ url_for('main.home') }}">Add some recipes!</a></h3>
    {% endif %}
    {% for recipe in recipe_list.items %}
        <p class="content-section">
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('shopping.shopping_list_remove_recipe', recipe_id=recipe.id) }}">Remove</a>
            <a class="article-title" href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}"">{{ recipe.title }}</a>
        </p>
    {% endfor %}
    {% for page_num in recipe_list.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if recipe_list.page == page_num %}
                <a class="btn btn-primary mb-4" href="{{ url_for('shopping.shopping_list', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-primary mb-4" href="{{ url_for('shopping.shopping_list', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}